= Neovim plugin for editing Lisp and Scheme files

This is a Neovim native-Lua implementation of the Scheme/Lisp
indenter of https://github.com/ds26gte/scmindent (see description
there). It doesn't require any external programs.

== Installation

This package contains the files

  autoload/neoscmindent.vim
  lua/neoscmindent.lua
  after/indent/lisp.vim

Copy them to the `autoload`, `lua`, and `after/indent` subdirectories respectively,
somewhere in your Neovim `'runtimepath'` (aka `'rtp'`). Unless
you're doing something atypical, your `'rtp'` includes
the directory `~/.config/nvim`, so you could do:

   # ensure that the relevant subdirectories in your rtp exist
   mkdir -p ~/.config/nvim/autoload
   mkdir -p ~/.config/nvim/lua
   mkdir -p ~/.config/nvim/after/indent

   # go to the directory created by this repo
   cd <this-repo-directory>

   # copy the files from the repo to the appropriate places in rtp
   cp -p autoload/neoscmindent.vim ~/.config/nvim/autoload
   cp -p lua/neoscmindent.lua ~/.config/nvim/lua
   cp -p after/indent/lisp.vim ~/.config/nvim/after/indent

Alternatively, clone this repo inside the `pack` subdirectory
somewhere in your `'rtp'`, using the path suggested in `:help
packages`. E.g., again assuming
`~/.config/nvim` is in your `'rtp'`, you could do

  # ensure that the relevant pack subdirectory exists
  mkdir -p ~/.config/nvim/pack/neoscmindent/start

  # go there
  cd ~/.config/nvim/pack/neoscmindent/start

  # clone this repo there
  git clone https://github.com/ds26gte/neoscmindent

Either approoach is not difficult, you don't really need a
3rd-party plugin manager, but I expect that would work too, not
that I've tried.

The `after/indent/lisp.vim` is just for convenience. You may want
to trigger the indenter in your own way, especially if you
already have a familiar setup for your Scheme and Lisp (or other
Lisp-y) files. Whatever you do, you have to make sure that the
local option `'indentexpr'` (aka `'inde'`) is set for the files
that you want indented by Neoscmindent, i.e.,

  setl inde=neoscmindent#GetScmIndent(v:lnum)

You also need to ensure that the options `'lisp'` and
`'equalprg'` (aka `'ep'`) are _not_ set, so `'inde'` can come
into its own.

(`'lisp'` is Vim's own attempt at indenting Lisp. It's less
featureful than Neoscmindent, and also occasionally buggy.)

(`'equalprg'` is used to call an external-program indenter, e.g.,
the kinds provided in Neoscmindent's parent software,
https://github.com/ds26gte/scmindent. If you're using Neovim,
then Neoscmindent is the better choice as it runs natively in
Neovim without requiring an external program in a language that
you may not have installed. If you're using Vim, well, Scmindent
is your only choice.)

(If you're wondering why the repo doesn't provide an
`after/indent/scheme.vim` provided, this is because Vim's
`indent/scheme.vim` takes care of loading any and all
`indent/lisp.vim` filess that are present.)

== Customization

Neoscmindent uses keyword info from `~/.lispwords.lua`. Here is
an example `~/.lispwords.lua`: It's simply a Lua file that
returns a Lua table associating keywords with their proposed
indentation styles:

  return {
    ['call-with-input-file'] = 1,
    ['case'] = 1,
    ['do'] = 2,
    ['do*'] = 2,
    ['fluid-let'] = 1,
    ['lambda'] = 1,
    ['let'] = 1,
    ['let*'] = 1,
    ['letrec'] = 1,
    ['let-values'] = 1,
    ['unless'] = 1,
    ['when'] = 1,
  }

As you can see, each keyword is assigned a number, which we call
its "Lisp indent number", or LIN for short. Let's say a keyword
`quayword` has a LIN `n`. A form `(quayword S1 S2 \...)` can occur
either on a line by itself or it can be split across lines.

If the form is on a line by itself, the
subforms need no indentation.

If it splits such that `Si` is on
the second line, then the indentation of `Si` depends on whether
`i` is greater than `n`.

If `i \<= n`, then `Si` is indented 3 columns past (the beginning
of) `quayword`.

If `i > n`, then `Si` is indented just one column past (the
beginning of) `quayword`.

The same holds true if the form is split across more than two
lines.

=== Keywords not mentioned in `~/.lispwords.lua`

If a keyword is present in the option `'lispwords'` (aka `'lw'`),
then absent an entry in `~/.lispwords.lua` it will be assumed to
have a LIN of 0.

Any keyword that starts with `def` is
assumed to have LIN 0, unless overridden in `~/.lispwords.lua`.
(This is because Lispers tend to create ad hoc definer keywords,
whether procedure or macro, whose names start with `def`, and
which they expect to indent like `define` or `defun`.)

If a keyword is neither in `.lispwords.lua` nor in `'lispwords'`,
then it is assumed to have a LIN of `-1`. In this case, if the
first subform is on the second line, then it and any subsequent
lines are aligned directly under the keyword. If the first
subform stays on the same line as the keyword, then any
subsequent lines are aligned directly under the first subform.
